version: "3"
services:
  server:
    image: yandex/clickhouse-server:19.13
    restart: always
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    volumes:
      - ./container-data/clickhouse/data:/var/lib/clickhouse
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
  client:
    image: yandex/clickhouse-client:19.13
    command: ['--host', 'server']
