version: "3"

networks:
  default:
    driver: bridge

services:
# =============== Spark services ===============
  spark-master:
    image: bde2020/spark-master:2.4.1-hadoop2.7
    hostname: spark-master
    networks:
      - default
    environment:
      SPARK_PUBLIC_DNS: 0.0.0.0
      INIT_DAEMON_STEP: setup_spark
      #SPARK_DEPLOY_DEFAULTCORES: 2
    expose:
      - 4040
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
      - 20021:20021
    volumes:
      - ./container-data/spark-master/conf:/conf
      - ./container-data/spark-master/data:/tmp/data
      - ./container-data/spark-master/work:/spark/work
      - ./container-data/spark-allnodes:/jar
      - ./container-data/spark-allnodes:/etc/spark/apps

  spark-worker-1:
    image: bde2020/spark-worker:2.4.1-hadoop2.7
    networks:
      - default
    depends_on:
      - "spark-master"
    hostname: spark-worker-1
    environment:
      SPARK_MASTER: spark://spark-master:7077
      SPARK_PUBLIC_DNS: 0.0.0.0
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 3g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    ports:
      - 8081:8081
    volumes:
      - ./container-data/spark-worker-1/config:/conf
      - ./container-data/spark-worker-1/data:/tmp/data
      - ./container-data/spark-worker-1/work:/spark/work
      - ./container-data/spark-allnodes:/jar
      - ./container-data/spark-allnodes:/etc/spark/apps

  spark-worker-2:
    image: bde2020/spark-worker:2.4.1-hadoop2.7
    networks:
      - default
    depends_on:
      - "spark-master"
    hostname: spark-worker-2
    environment:
      SPARK_MASTER: spark://spark-master:7077
      SPARK_PUBLIC_DNS: 0.0.0.0
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 3g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8882
    ports:
      - 8082:8082
    volumes:
      - ./container-data/spark-worker-2/config:/conf
      - ./container-data/spark-worker-2/data:/tmp/data
      - ./container-data/spark-worker-2/work:/spark/work
      - ./container-data/spark-allnodes:/jar
      - ./container-data/spark-allnodes:/etc/spark/apps
