version: '3'
services:
  postgres:
    image: postgres:10
    restart: always
    ports:
    - 5555:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: course
      POSTGRES_USER: admin
      PGDATA: /tmp
    volumes:
    - ./container-data/postgres/data:/var/lib/postgresql/data
    - ./container-data/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
